### ISSUE TITLE
Cannot load in browser with require.js

### ISSUE THREAD

**Issue by parisk** [dworthen/js-yaml-front-matter#11]
Attempting to load js-yaml-front-matter in the browser with require.js results in `Uncaught TypeError: Cannot set property 'parse' of undefined`.
## js-yaml-front-client.min.js

![image](https://cloud.githubusercontent.com/assets/1188592/14200681/31d8bf5c-f7f5-11e5-8a1f-53f5e6f0ee92.png)
## js-yaml-front-client.js

![image](https://cloud.githubusercontent.com/assets/1188592/14200693/5491915e-f7f5-11e5-96f1-886176ae3e76.png)

**Comment by malbernaz** [comment]
+1

**Comment by umaganesan** [comment]
following

**Comment by dworthen** [comment]
Resolved in the upcoming release. Please grab the latest browser umd script from the [4.0.0 branch](https://github.com/dworthen/js-yaml-front-matter/tree/v4.0.0-3).  Or install from npm using the next tag, `npm install yaml-front-matter@next`.
