### ISSUE TITLE
 Define __content from API

### ISSUE THREAD

**Issue by carlskii** [dworthen/js-yaml-front-matter#3]
Is there a way to define the  `__content` name when using the API ? 

I see there's a -c that can be used from the command line. 

Thanks.

**Comment by dworthen** [comment]
Yes, the second argument to the loadFront method is the content key name you wish to use. 

```
yamlFront.loadFront('content to process', 'myKeyValue');
```

Check out the loadFront method in the API section of the readme for more info. 

Hope this helps.
