### ISSUE TITLE
Demo for use in browser unavailable

### ISSUE THREAD

**Issue by chtixof** [dworthen/js-yaml-front-matter#4]
Hello.

You wrote at the top of the README.md:
> Works in the browser as of 3.0.0. [Online Demo](http://js-yaml-example.derekworthen.com/).

But http://js-yaml-example.derekworthen.com/ returns a 502 error.

Actually, I would like to ajax-read a md file with a front matter from a browser, parse the front matter and render the md content with marked.js... And I'd like to see a demo...

Thanks

**Comment by dworthen** [comment]
Sorry for the delay. The online demo is available again but it is using an older version of the yaml-front-matter library so be sure to check out the api in the readme. Index.js in the examples directory shows how to use the updated client side library. The online demo is doing what you desire except without the ajax request.
